language: csharp
solution: SandwichClub.Api.sln
dotnet: 1.0.0-preview2-003131

install:
  # Restore dependencies
  - dotnet restore src/SandwichClub.Api/

script:
# Build projects
  - dotnet build src/SandwichClub.Api/
  - dotnet pack src/SandwichClub.Api/
    # Run tests